window.ASPECT_ARCHIVE = [
  { name: "Black ballerina", src: "/assets/archive/black-ballerina.webp", width: 675, height: 1200 },
  { name: "Black dune", src: "/assets/archive/black-dune.webp", width: 900, height: 1200 },
  { name: "Black half", src: "/assets/archive/black-half.webp", width: 960, height: 1200 },
  { name: "Dark chaos", src: "/assets/archive/dark-chaos.webp", width: 766, height: 1148 },
  { name: "Dusty pink aspect", src: "/assets/archive/dusty-pink-aspect.webp", width: 675, height: 1200 },
  { name: "fuchsia plant", src: "/assets/archive/fuchsia-plant.webp", width: 900, height: 1200 },
  { name: "Grey touch", src: "/assets/archive/grey-touch.webp", width: 960, height: 1200 },
  { name: "Red aspect", src: "/assets/archive/red-aspect.webp", width: 675, height: 1200 },
  { name: "red bird eye", src: "/assets/archive/red-bird-eye.webp", width: 675, height: 1200 },
  { name: "Red queen", src: "/assets/archive/red-queen.webp", width: 818, height: 1200 },
  { name: "White armour", src: "/assets/archive/white-armour.webp", width: 834, height: 1200 },
  { name: "White bird eye", src: "/assets/archive/white-bird-eye.webp", width: 752, height: 1200 },
  { name: "White elf", src: "/assets/archive/white-elf.webp", width: 960, height: 1104 },
  { name: "white eye", src: "/assets/archive/white-eye.webp", width: 675, height: 1200 },
  { name: "White sharm", src: "/assets/archive/white-sharm.webp", width: 675, height: 1200 },
  { name: "White swan", src: "/assets/archive/white-swan.webp", width: 960, height: 1200 },
  { name: "Wine half", src: "/assets/archive/wine-half.webp", width: 675, height: 1200 },
  { name: "Wine shelter", src: "/assets/archive/wine-shelter.webp", width: 960, height: 1200 },
];
